addons:
  sonarcloud:
    organization: "gulen" # the key of the org you chose at step #3
    token:
      secure: "6c21555e0ae78714a8e76edca77d777206256e5b" # encrypted value of your token
jdk:
  - oraclejdk9
script:
  - mvn clean verify sonar:sonar -Pcoverage -Dsonar.projectKey=gulen_6c21555e0ae78714a8e76edca77d777206256e5b
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'